[package]
name = "wev"
version = "0.1.0"
edition = "2021"

[dependencies]
combine = "4.6.6"
crossterm = "0.27.0"
ratatui = "0.25.0"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"], default-features = false }

[[bin]]
name = "wev"
path = "src/bin/main.rs"
